# Generated by Django 2.2.6 on 2019-10-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=20)),
                ('movieDirector', models.CharField(max_length=20)),
                ('movieRating', models.CharField(max_length=20)),
                ('movieRunningTime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theaterName', models.CharField(max_length=20)),
                ('region', models.IntegerField()),
                ('spot', models.IntegerField()),
                ('pos', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'theaters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MoiveSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movies')),
                ('Theater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Theaters')),
            ],
            options={
                'db_table': 'movieschedules',
                'managed': True,
            },
        ),
    ]
