# Generated by Django 2.2.6 on 2019-10-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoiveSchedules',
            new_name='MovieSchedules',
        ),
    ]
