# Generated by Django 2.2.6 on 2019-10-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191015_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieschedules',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MovieSchedules', to='movies.Movies'),
        ),
    ]
