# Generated by Django 2.2.6 on 2019-10-31 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.TextField()),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('movieRating', models.TextField()),
                ('duration', models.IntegerField()),
                ('genre', models.TextField()),
                ('userRating', models.FloatField()),
                ('imgUrl', models.TextField()),
                ('nation', models.TextField()),
            ],
            options={
                'db_table': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Theaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theaterName', models.TextField()),
                ('regionCode', models.CharField(max_length=10)),
                ('theaterCode', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('brand', models.CharField(max_length=30)),
                ('updatedTime', models.DateTimeField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'theaters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField()),
                ('totalSeat', models.IntegerField()),
                ('availableSeat', models.IntegerField()),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('roomProperty', models.CharField(max_length=30)),
                ('scheduleDate', models.IntegerField()),
                ('subtitle', models.BooleanField(null=True)),
                ('dubbing', models.BooleanField(null=True)),
                ('digitalized', models.BooleanField(null=True)),
                ('lateNight', models.BooleanField(null=True)),
                ('morning', models.BooleanField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Movies')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.Theaters')),
            ],
            options={
                'db_table': 'movieschedules',
                'managed': True,
            },
        ),
    ]
