# Generated by Django 2.2.6 on 2019-10-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theaters',
            old_name='raditude',
            new_name='latitude',
        ),
    ]
