# Generated by Django 2.2.6 on 2019-10-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191014_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='subsriber',
            new_name='subscriber',
        ),
    ]
